// Auth Constants
export {
    USER_TYPES,
    USER_ROLES,
    USER_STATUS,
    EMAIL_DOMAINS,
    PASSWORD_REQUIREMENTS,
    PASSWORD_ERROR_MESSAGE,
    API_ENDPOINTS,
    APP_ROUTES,
    ANIMATION_DURATION,
    DEBOUNCE_DELAY,
    TOAST_DURATION,
} from './auth.constants.js';

// Validation Constants
export {
    DOCTOR_SPECIALIZATIONS,
    VALIDATION_ERRORS,
    SUCCESS_MESSAGES,
    GENDER_OPTIONS,
    BLOOD_GROUP_OPTIONS,
    AGE_LIMITS,
    LICENSE_FORMAT,
    PHONE_FORMAT,
    FORM_PLACEHOLDERS,
    FORM_LABELS,
} from './validation.constants.js';
